[package]
name = "hw4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
async-channel = "1.5"
tokio = { version = "1", features = ["full"] }
scoped-tls = "1.0.1"